# Generated by Django 5.1 on 2024-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_assignmentfile_remove_assignment_research_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
