# Generated by Django 5.1 on 2024-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
