# Generated by Django 4.2.13 on 2024-06-06 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_user_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
