# Generated by Django 5.1 on 2024-08-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_assignment_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submitted',
        ),
    ]
