# Generated by Django 5.1 on 2024-08-22 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_submission_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='marks',
            name='max_marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=5, null=True),
        ),
    ]
