# Generated by Django 4.2.13 on 2024-06-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_assignment_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='teacher_id',
            new_name='user_id',
        ),
    ]
