# Generated by Django 5.1 on 2024-08-23 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_submission_plagiarism_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcourse',
            name='credit_hour',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
