# Generated by Django 5.1 on 2024-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_programcourse_credit_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='accepted_file_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
