# Generated by Django 5.0.6 on 2024-08-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0011_alter_student_user_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
